### ISSUE TITLE
Gherkin info

### ISSUE THREAD

**Issue by tomatobrown** [mvalipour/specflow-report-templates#2]
Hi,
I'm having some trouble getting the Gherkin steps to show on a failing test.  I don't see how to have that working.  I see you have a TestResult.txt file, but I'm not sure where that came from and how it's being used.

love the design btw
-tomato

**Comment by mvalipour** [comment]
Hi,

It's probably too late, but I will reply to this in case it was useful to any other person.

As stated in the **Usage**, you need to get your specflow report generator to output the `.txt` file for you. See [here](https://github.com/techtalk/SpecFlow/wiki/Reporting) for instructions.
